### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by micw** [Maxr1998/home-assistant-Android#10]
Thank you for the app, that's great. I'd like to give some general feedback:
- 1st, it works with no serious issues ^^
- apk name should be less generic. There's no "save as..." when you download with android, so the file should be "home-assistant-client-0_2.apk" or similar.
- In intial setting dialog it's a bit unclear what port/protocol is used when one enters the ip address. I suggest to accept only valid URLs
- Password should be optional
- Optionally, basic authentication should be supported
- There's no way to change settings after first connect (need to uninstall/reinstall to change ip)
- The main screen should be more compact. Maybe more than one group per row should be allowed. I have one tablet mountet at the kitchen wall that shows my house status - it would be great if all would fit on it
- Home Assistant allows groups with "view:yes" as individual screens. It would be nice to select one of these in the settings which is displayed instead of default_view. Then I could create a special tablet group with reduced amount of data
- Lights with brightness control should have a slider in addition to the switch and should show the current brightness
- Sun-Item only shows the "Sun" label, no icon, no information
- Item icons are missing

**Comment by Maxr1998** [comment]
Thanks for your feedback!
>- apk name should be less generic. There's no "save as..." when you download with android, so the file should be "home-assistant-client-0_2.apk" or similar.

Sure, I'll do that for the next version. It just what Android Studio names it by default atm.
Also, I want to publish it to Google Play, but first I have to proof some long-time commitment that balloob marks this as official app and I can ask Google Play to unlock my listing.
>- In intial setting dialog it's a bit unclear what port/protocol is used when one enters the ip address. I suggest to accept only valid URLs

IP address can be added in `protocol://ip.xyz:port/` pattern. I'll make it more clear to users.
>- Password should be optional

Yes, I didn't test it on unprotected instances yet.
>- Optionally, basic authentication should be supported

What do you exactly mean with that?
>- There's no way to change settings after first connect (need to uninstall/reinstall to change ip)

Well, you could turn off and on again Wi-Fi, that allows you to modify the settings. ButnI will add a logout button, too.
>- The main screen should be more compact. Maybe more than one group per row should be allowed. I have one tablet mountet at the kitchen wall that shows my house status - it would be great if all would fit on it

Tablet layout is already on my list. Should be easily possible with a modified StaggeredGridLayoutManager for the RecyclerView.
>- Home Assistant allows groups with "view:yes" as individual screens. It would be nice to select one of these in the settings which is displayed instead of default_view. Then I could create a special tablet group with reduced amount of data

Good idea! Should be definitely possible :grinning:
>- Lights with brightness control should have a slider in addition to the switch and should show the current brightness

That already exists, you can long-press light entities with brightness-support to reveal a slider. It's a little hidden still. Gonna take a look how I can improve usability on this.
>- Sun-Item only shows the "Sun" label, no icon, no information

Noticed that too, didn't look into it yet.
>- Item icons are missing

Seems like a regression from indev. Gonna fix soon.

**Comment by micw** [comment]
Basic auth: When I expose something to the public internet, I put nginx in front that does http basic authentication (username+password) and https via letsencrypt. It would be great if you support this by adding settings for it and create the required auth header.

Brightness slider: It would be ideal to have them below or right of the label if it's a dimmer.

**Comment by LuccoJ** [comment]
> That already exists, you can long-press light entities with brightness-support to reveal a slider. It's a little hidden still. Gonna take a look how I can improve usability on this.

Aside from being a bit hidden (but then again it's relatively standard Android stuff to long-press to bring up additional option), I find it very unintuitively because you must not *release* the press, and just directly proceed to sliding... and worse, that doesn't work right away, I have to "wiggle" the bar with my finger a bit before it actually starts registering the movement.

**Comment by Maxr1998** [comment]
@LuccoJ the way I currently designed it was intentional, because I thought it'd be pretty cool to be able to change brightness with one touch and a following swipe, the extra "wiggle" was implemented that you can preview the current brightness level and don't change it by mistake - but I agree, the UX is pretty unintuitive AND hidden right now, so I will definitely change it.

**Comment by LuccoJ** [comment]
One thing you could do (no idea about the difficulty of implementation, but I think I've seen similar in some other apps) is to still have long-press, but have it result in a pop-under with the brightness; then the user would see the current brightness immediately, and could either move their finger downwards into the slider and change it, or quite possibly release the touch, and change it with a second touch (the two methods don't really have to interfer with one another).

**Comment by Maxr1998** [comment]
@LuccoJ This is actually a pretty good idea, which would still allow me to keep the current touch-change-release option. Had something different in mind.. thanks!

**Comment by marksev1** [comment]
Is there a thread on the HASS forum about this? Where we could see screenshots, of the phone and wear UI?

**Comment by Maxr1998** [comment]
@marksev1 actually, I didn't think of that yet. Will create one when I have time today or tomorrow.

**Comment by HeaDBanGer84** [comment]
1. First thank you for the graet app! 
2. I also only dicovered the brigthness control through reading this issue.
3. Can you implement something similar to the brightness for assigning temperature to thermostats?
