### ISSUE TITLE
Support http basic authentication

### ISSUE THREAD

**Issue by Maxr1998** [Maxr1998/home-assistant-Android#13]
- [x] Better hint IP/port syntax
- [x] Don't ask for password if none is set
- [x] Allow basic http-authentication
- [x] Allow logout

**Comment by Maxr1998** [comment]
Since I have no basic auth protected instance myself to test, I'd need someone to provide one to me.

**Comment by micw** [comment]
Thank you for reply. I have no running installation yet (I'm still on openhab2, ongoing migration to hass). I try to get one running this weekend.

**Comment by Charliedean** [comment]
Hi,
Please check out the following:
https://stackoverflow.com/questions/1968416/how-to-do-http-authentication-in-android
The second answer seems the simplest implementation.  

The following is how to setup basic auth on Nginx:
https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10

And finally how to use nginx as a reverse proxy for home assistant:
https://home-assistant.io/docs/ecosystem/nginx/  
You only really need the nginx configuration.

Please reach out to me if you need any help.
Thanks
Charlie

**Comment by Maxr1998** [comment]
I use OkHttp, so I already know how to do it. I just need an instance for testing, but I don't want to spend a lot of time setting up nginx on my machine just for this little feature.. it would be eaiser if someone who already has their own nginx instance running with hass allowed me to test on it..

**Comment by micw** [comment]
@Maxr1998 sorry, I promised you a setup but did not find the time. I have set you up https://hademo.vpsprod2.wyraz.de/demo/ (log in with: user / password) which is a proxy to the official home assistant demo plus basic auth. Hope that helps and sorry for the delay!

**Comment by Maxr1998** [comment]
@micw thanks a lot! This is very helpful for me ☺️ 
It seems though the the official demo doesn't have the websocket api exposed, could you possibly set the url to `https://m-home.ddns.net` please?

**Comment by micw** [comment]
Done. There are some tricks to make websockets work with nginx reverse proxy, please try if that works. I also removed the /demo/, so just use https://hademo.vpsprod2.wyraz.de/

**Comment by Maxr1998** [comment]
@micw thanks a lot! Btw, I just noticed that you seem to run the blog.fefe.de, good job! I'm not a regular reader, but I remember one post being quite helpful to me a few months ago - not sure what it was about though, maybe Arduino or ESP8266? Anyway, thanks again!

**Comment by micw** [comment]
@Maxr1998 No, I'm not related with fefe's blog. But if you mention arduino, you probably meant https://blog.wyraz.de - here I blog from time to time about projects and experiences.
At the moment I'm switching completely oevr from home-grown stuff+openhab2 to home assistant - meanwhile I'm automating my garden sprinkler and water system using esp8266 modules. I hope I find the time to document everything to my blog.

**Comment by Maxr1998** [comment]
@micw oh, ok. I figured because of that backup repo.. guess I was wrong then.
I might also have stumbled over your blog once, at least the name seems familiar..

**Comment by Maxr1998** [comment]
@micw I'm currently continuing testing after my holidays, but the server times out. Did you change anything in your config?

**Comment by micw** [comment]
No idea why it stopped to work. I just redeployed my webserver, now it should work.

**Comment by Maxr1998** [comment]
@micw It seems to be broken again. Server returns bad gateway, but connecting to the url directly still works.. I finished the code though, only need some last testing now.

**Comment by micw** [comment]
@Maxr1998 Seems that nginx caches the IP address forever so when it changes, it fails.
I restarted and added a auto-restart cron every night.

**Comment by Maxr1998** [comment]
Fixed as of b2e9e09bbb124375ac05a6046f485fc3636e10c1!

**Comment by micw** [comment]
@Maxr1998 Great work. Looking forward to get a release to give it a try :-)
May I switch off my reverse proxy now?

**Comment by Maxr1998** [comment]
@micw Thanks! Yes, you can switch off the proxy now if you want :)
If it isn't too much of a hassle and doesn't cost you though, I'd love if you could just keep it running for occasional unit testing after related changes :relaxed:

_Gesendet von meinem Huawei Nexus 6P mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
