### ISSUE TITLE
Accept self signed ssl / handle ssl errors

### ISSUE THREAD

**Issue by vpnmaster** [Maxr1998/home-assistant-Android#14]

**Comment by Maxr1998** [comment]
That should not be an issue, normally. Did you input `https://<ip>:<port>` into the adress bar?
Could you send me your logcat output if Android really doesn't accept your certificate?

**Comment by vpnmaster** [comment]
I'm using let's encrypt ssl to access home assistant outside my network. In my local lan the ssl is invalid if I hit hass with the internal ip. I can skip the warning in browsers.

**Comment by Maxr1998** [comment]
Ok, I know what's the issue, and can reproduce. Fixing it soon.
