### ISSUE TITLE
Support Android < 5.0 (API-21)

### ISSUE THREAD

**Issue by fabaff** [Maxr1998/home-assistant-Android#16]
The installation of the [`apk`](https://github.com/Maxr1998/home-assistant-Android/releases/download/v0.2/app-release.apk) fails on 4.4.2 with a parsing error.

**Comment by Maxr1998** [comment]
Yes, the apk is built with a minSdkVersion of 21, aka Android 5.0. I'm currently not sure I want to have the hassle of supporting older versions as well, sorry.

**Comment by fabaff** [comment]
Thanks. I wasn't sure where the issue could be because this tablet was the only available device to run a test.

**Comment by Maxr1998** [comment]
Oh ok, I see. I suppose your Tablet is too old to get any upgrade? I will look how much work it would be to support at least 4.4+, KitKat is only one API version actually, and shouldn't be too much of a difference with support libs. Reopening for now until I make a final decision.

**Comment by Kernald** [comment]
Just a note: as you don't use the SAF, if you support API 19, you probably could support API 17 and 18 too without any more work.
