### ISSUE TITLE
Gradle wrapper is missing

### ISSUE THREAD

**Issue by Kernald** [Maxr1998/home-assistant-Android#26]
The Gradle wrapper is missing from the repository (`gradlew`/`gradlew.bat`). It makes the build without Android Studio much more complicated.

**Comment by Kernald** [comment]
Wow that was fast, thanks!

**Comment by Maxr1998** [comment]
It was easy enough to still do it this evening :blushed:

There still will be a build error though, you need to remove the signing config from the build.gradle in the meantime.

**Comment by Maxr1998** [comment]
Fully fixed with 3e2e80e2684c89418fc1b9396f9a0f6c6867d661.
