### ISSUE TITLE
App is showing a white screen with no way to get front end back 

### ISSUE THREAD

**Issue by pizzapants** [Maxr1998/home-assistant-Android#27]
Not sure what caused this, possibly opening the app while HASS was restarting (just a guess) but now when I open it, it just shows a blank white screen (with the blue home assistant header). Pressing refresh or forcequitting the app doesn't fix it. Short of uninstalling/reinstalling, it seems to be no way to get the front end back.

**Comment by Maxr1998** [comment]
I experienced the same while restarting Home Assistant (it of course can't really connect but also doesn't throw any Exception), but a simple restart of the app fixed it. Since you said "refresh button" I suppose you're still running the 0.1 or 0.2 version, could you try with the latest version (1.0-RC1) or build the current master yourself?

**Comment by pizzapants** [comment]
Oh, sure. I assumed f droid had the latest, sorry! Not sure how to build it myself, where can I download the latest?

**Comment by Maxr1998** [comment]
@pizzapants Max:
Here on GitHub! :) I wonder why F-Droid isn't updated though, shouldn't it build automatically on new release tags?

**Comment by pizzapants** [comment]
@Maxr1998 Is there an APK on here that I can download? Not seeing it, sorry! 

Strange, latest version on FD is .2

**Comment by Maxr1998** [comment]
Look at the [releases page](https://github.com/Maxr1998/home-assistant-Android/releases/tag/v1.0-rc1).

**Comment by pizzapants** [comment]
@Maxr1998  cheers, thanks. Derp.

**Comment by pizzapants** [comment]
@Maxr1998  just a heads up, trying to upgrade to the new version gives the following error: app not installed, package conflicts with an existing package by the same name. 

Strangely, upon removing the old version and installing the new one, Im still greeted with the blank white screen.

**Comment by Maxr1998** [comment]
First thing is normal, F-Droid signs the builds with its own certificate, the GitHub releases are signed with mine, thus Android doesn't allow upgrading.

For the other stuff, could you send me a log (adb logcat)?
I really don't know what could be causing this. Any specialties in your home assistant configuration?

**Comment by pizzapants** [comment]
@Maxr1998 
Makes sense. 

Yeah, ill try to do that tonight. Dont think so, my whole config is up on my github page though if you want to look.

**Comment by pizzapants** [comment]
@Maxr1998 by the time I got to look it up, I didnt see anything in my logcat about it and I couldnt get it to repeat the issue. Seems to work ok now, Ill keep you posted.

**Comment by Maxr1998** [comment]
Since it seems to work fine with the latest version, I am closing this issue now. If you happen to get into this again in the future, just leave a comment and reopen ☺️

**Comment by castorinop** [comment]
in my case, the white screen appears when dont have defined groups.

**Comment by coolbombom** [comment]
@castorinop 

i have the same problem

**Comment by Maxr1998** [comment]
Good point, it should display the default groups then.
