### ISSUE TITLE
Invalid password on current master branch

### ISSUE THREAD

**Issue by w1ll1am23** [Maxr1998/home-assistant-Android#31]
Downloaded the release candidate version and it works, but when building from the current master branch I am not able to authenticate, I get a toast indicating my password is invalid.
Not using basic auth.
I am accessing HA remotely through an Nginx reverse proxy using lets-encrypt certs.

Also, I am not seeing a persistent notification indicating a login failure which I do see on the RC version when actually using a bad password.

Let me know if there is anything else I should try.

Also, I just started a new job as an Android developer so I plan on following this pretty closely and attempting to contribute where/when I can.

**Comment by Maxr1998** [comment]
@w1ll1am23 Hi! Thanks for the report, and the offer to contribute! That would be very appreciated :)
On your issue, could you send me a logcat of the login process? I'd need to know if there's any http error or what warnings/errors my authentication process logs.

**Comment by w1ll1am23** [comment]
@Maxr1998 sure thing, https://pastebin.com/JntX9k2e 

I have been looking at this since I opened it can can't figure out what is going on, but I am new to Android so that doesn't mean much.

**Comment by Maxr1998** [comment]
@w1ll1am23 Ok, nothing special visible in the logs. At least we now know that the socket connection works fine, and that there _is_ a response from the Home Assistance instace.
Could you repeat your logging again, but this time with Log.d(TAG, message.toString() added directly after https://github.com/Maxr1998/home-assistant-Android/blob/master/app/src/main/java/io/homeassistant/android/HassService.java#L250?

**Comment by w1ll1am23** [comment]
Ahhh there ya go. I was wondering if those extra keys were causing the problem, but wasn't sure how they got added in.

This is from the send method
```
06-27 15:39:40.095 28801-28837/io.homeassistant.android D/HassService: send: {"api_password":"MY_PASSWORD","type":"auth","$change":null,"serialVersionUID":1751593233156997204}
```

This is from the on message received.
```
06-27 15:38:01.306 27844-27949/io.homeassistant.android D/HassService: onMessage: {"message":"Message incorrectly formatted: extra keys not allowed @ data['$change']. Got None\nextra keys not allowed @ data['serialVersionUID']. Got 1751593233156997204","type":"auth_invalid"}

```

**Comment by w1ll1am23** [comment]
I don't think it matters, but I commented out

```
import io.homeassistant.android.location.LocationUpdateReceiver;
```

and everything in 
```
updateLocationTracker
```

In the settingsActivity because that package doesn't exist...

**Comment by Maxr1998** [comment]
Ah, so that's the cause! This is actually an upstream bug of the Ason library, whose serializer also includes compiler-generated fields. Luckily, you can easily fix this (for now) by just disabling instant run in Android Studio - then it always has to do a full build, but at least these fields don't get included.

**Comment by Maxr1998** [comment]
It actually does, even two times ;) [[1](https://github.com/Maxr1998/home-assistant-Android/blob/master/app/src/gms/java/io/homeassistant/android/location/LocationUpdateReceiver.java)]

It's just not in the ´main´ source set because it's flavor-dependent.

**Comment by w1ll1am23** [comment]
Ahhh okay awesome, disabling instant run worked. Thanks for the help.

**Comment by Maxr1998** [comment]
Glad you could fix it! As I said, looking forward to any contribution, no matter how big or small :)

**Comment by dixonl90** [comment]
I just ran into the same issue, and have been pulling my hair out why the auth wasn't working. It might be worth putting a note in the README about the Instant Run incompatibility with Ason.

**Comment by Maxr1998** [comment]
@dixonl90 actually, a fix was merged into Ason just two days ago, and since I'm currently building from my own fork anyway until there is a new upstream release, you can use Instant run without any problems now ;)

**Comment by dixonl90** [comment]
Fab, thanks for the update. :)

**Comment by MrManor** [comment]
Hi guys. For one like me which is not a developer: Is this still a problem and is there any way to use this app as of today? I have downloaded it from F-droid recently and I am unable to login.

**Comment by Maxr1998** [comment]
Hi @MrManor, no, the problem you're having is probably not related to this issue - I suppose it's more caused by the new login system Home Assistant uses now. I didn't get around to support that yet, however, the app should still work if you enable the legacy api key - that's at least how I use it atm.

**Comment by MrManor** [comment]
> the app should still work if you enable the legacy api key
Ok, thanks. I'll try using legacy key.
