### ISSUE TITLE
Usage of location and battery tracking

### ISSUE THREAD

**Issue by DJaeger** [Maxr1998/home-assistant-Android#32]
How can I use the location and battery tracking of this app.
I have activated it within the app, but it doesn't appear in the known devices.
As of the source code its using device_tracker.see
But I can not find any documentation how to set it up.

I'm using hass-1.0-phone-fdroid.apk with Home Assistant
0.50.1.

**Comment by Maxr1998** [comment]
You need to specify a device name for it to work - I will probably add a better tutorial soon.

**Comment by DJaeger** [comment]
You mean in the app settings or do I have to add it manually to my known_devices.yml ?

Within the app settings I have specified a device name.

**Comment by Maxr1998** [comment]
Then it should already work :thinking:
Maybe you have to add the device_tracker component to your configuration?

**Comment by DJaeger** [comment]
Which device_tracker component?
I have FritzBox and Locative already in my config.

Do I have to add
```yml
device_tracker:
  - platform: see
```
?

**Comment by orx57** [comment]
Hello,

Please can you clarify which platform to configure for the device tracker component?

Thanks!
