### ISSUE TITLE
Translate button is not working

### ISSUE THREAD

**Issue by DJaeger** [Maxr1998/home-assistant-Android#34]
The translate button in the settings is not working.
It seems to get the pressed state, but nothing happens.

I'm using hass-1.0-phone-fdroid.apk

**Comment by Maxr1998** [comment]
@DJaeger I believe it happens because you don't have Chrome installed. I need to tweak the fallback intent that another browser can be launched as well.

**Comment by DJaeger** [comment]
I have Chromium installed, but why force a specific browser?

I also do not like to be forces to use an online service to translate.
For me its much easier to translate with a git fork.
But I think it will be overwritten while building.

**Comment by DJaeger** [comment]
I think that is also the reason, why opening the web gui is not working.

**Comment by Maxr1998** [comment]
The browser gets "forced" because of my Chrome Custom tab implementation, It actually should fall back to the default browser if CCT isn't available. Will take a look soon.

**Comment by DJaeger** [comment]
I have looked into the CustomTab solutions by Telegram and a SoundCloud demo app and they have implemented their own CustomTabsClient

**Comment by Maxr1998** [comment]
Interesting. Maybe I also need to do that.

**Comment by DJaeger** [comment]
I think the code could be reused almost completely. 
You should only rename the methods and so on, as they are prefixed with "Telegram".
