### ISSUE TITLE
Using self signed certificate only shows "Connection errror: Invalid IP, or is the server offline?"

### ISSUE THREAD

**Issue by e-alfred** [Maxr1998/home-assistant-Android#37]
Hello,

I set up a self signed certificate as shown here:

https://home-assistant.io/docs/ecosystem/certificates/tls_self_signed_certificate/

Connecting to my Homeassistant instance only leads to this error after clicking "connect" on the login page. I set a password too. The web ui works flawlessly. I installed 1.0 from F-Droid on a BQ X5 Plus running Android 7.1.1. Home Assistant is on version 0.54.0.

**Comment by Maxr1998** [comment]
Could you capture a logcat for me that I can see the exact error message?
Thanks!

**Comment by PatrykKot** [comment]
I think I have the same problem. Got SSLHandshakeException when using self-signed certificate generated with linked resources.

**Comment by Maxr1998** [comment]
@PatrykKot could you send me the whole logcat?

**Comment by PatrykKot** [comment]
I have imported project to Android Studio. When I want to connect to HASS with self-signed certificate I only getthis in console:

`E/HassService: SSLHandshakeException while connecting to Socket, going to try again - Code null`

**Comment by Maxr1998** [comment]
@PatrykKot Ok, thanks. Probably the OkHttp doesn't allow self signed certificates by default. I will take a look at ir

**Comment by e-alfred** [comment]
I get this from a logcat output:
```

10-11 00:46:42.147  6563  6563 D Home Assistant URL: https://1.1.1.1:8123/api/websocket
10-11 00:46:42.737  6563  6721 E HassService: SSLHandshakeException while connecting to Socket, going to try again - Code null
```

**Comment by Maxr1998** [comment]
Fixed now in master. Sorry this took so long..
