### ISSUE TITLE
Better indicate that this app is unofficial

### ISSUE THREAD

**Issue by balloob** [Maxr1998/home-assistant-Android#38]
Let me start with that I appreciate the work you have done on this app. However, it is not clear enough from the [README](https://github.com/Maxr1998/home-assistant-Android/blob/master/README.md) or [F-Droid listing](https://f-droid.org/packages/io.homeassistant.android/) that this is an unofficial app. Please:

- [ ] Don't use the Home Assistant logo for your app
- [x] Don't use the Home Assistant name for your app
- [x] Don't link to the Home Assistant website as "website"
- [x] Update the description to mark it more clearly that this is an unofficial app

**Comment by Maxr1998** [comment]
@balloob Yep, I already thought about some changes to make clear that this is an unofficial app some days ago, however, I was pretty busy in the last few weeks (moved, started studying at University, etc). I'll try to implement the suggested changes as soon as possible.

**Comment by Maxr1998** [comment]
Started to work on the app again today, hope I'll find more time in the next few weeks. Searching a new name for the app now, then I'll also change the logo.
I can't do anything about the F-Droid listing though, I didn't create it actually, don't know how I can edit it.
Hopefully it will get updated after I change my README.

**Comment by HeaDBanGer84** [comment]
Isnt it better to call it frontend instead of client? Its more the language used in home assistant config.

**Comment by Maxr1998** [comment]
Client sounds more naturally, imo, so I think we should just keep that. Also, "client" more properly separates it from the actual Home Assistant `frontend` component.

**Comment by HeaDBanGer84** [comment]
Fine, good reasons to keep the name. Some rough sketch for a logo:
![hassdroid_logo svg](https://user-images.githubusercontent.com/11348045/35970342-55cad4e0-0cca-11e8-8634-00a8810bfee8.png)
far away from finished but you can imagine how it should look like. Perhaps somebody more artistic can do finish it.

**Comment by Maxr1998** [comment]
Looking good! Thanks for the contribution. Planning something very similar to this.

**Comment by HeaDBanGer84** [comment]
Thx that you like it. Have send you the .svg so that you can change it to your preferences.

**Comment by Maxr1998** [comment]
Just received it, thanks a lot! Will tweak it to my needs & convert it to Android's drawable format very soon!
