### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by Maxr1998** [Maxr1998/home-assistant-Android#39]
In accordance to #38, we need a new name for this app. Possible variations:
- HassClient
- Hass Client
- HassDroid
- Client for Home Assistant _(too long?)_
- HassControl
- Control for Home Assistant _(also too long?)_
- _other ideas?_ 

Also, the name needs to indicate the independence from the Home Assistant project and should have their approval.

(cc @balloob)

**Comment by balloob** [comment]
All above names have my approval 👍  Anything that is either "Home Assistant" or "Home Assistant X" is not ok. "X for Home Assistant" is fine.

**Comment by Maxr1998** [comment]
@balloob thanks! Which one would you prefer personally?

**Comment by renekliment** [comment]
I like HassDroid.

**Comment by Maxr1998** [comment]
@renekliment I kinda think the same, HassDroid makes it clear that it's specific to Android.
