### ISSUE TITLE
Support proper updating after posting events

### ISSUE THREAD

**Issue by Maxr1998** [Maxr1998/home-assistant-Android#4]
At the moment, it just fires off events and doesn't reload states until restarting the app.

**Comment by swbradshaw** [comment]
Great start with app! HassActivity needs to be refactored. All of the logic you currently have to connect and get events (LoginUtils, HassSocketListener,etc) needs to be moved out of the Activity and into a Service.  Putting it in a Service will allow things like Device Tracking and other future items to happen in the background, but also allow your Activity to connect to it for foreground updates.

**Comment by Maxr1998** [comment]
That was exactly my idea, we would also need a service to allow using shortcuts.
The service can then be bound by HassActivity or a ShortcutActivity.

**Comment by Maxr1998** [comment]
So, I restructured everything in ee9102adc24e46504cdff0bf1765856851004e3f, this should make things much easier.

**Comment by Maxr1998** [comment]
All ViewHolders use the `OnRequestResultListener` to properly update their states now, so this can be marked as fixed.
