### ISSUE TITLE
Clarify the "Home Assistant URL/IP" login field

### ISSUE THREAD

**Issue by rpatterson** [Maxr1998/home-assistant-Android#44]
I have my HA instance set up with it's own domain and LetsEncrypt SSL certs that work fine in the browser.  When I put that URL in the "Home Assistant URL/IP" field on the app login screen and use the same password but all I get is `Connection failure: Invalid password!`, which isn't surprising since my username is nowhere in the "Home Assistant URL/IP".

How is one supposed to log in correctly?  This should also be presented in the login UI.  Preferably, the UI includes different fields for the different pieces of data.

**Comment by Maxr1998** [comment]
The login UI doesn't support the new username/password OAuth login yet, and since I don't really have the time to implement this, it'll stay that way for a while. However, you should be able to just use a long-term token, which you can generate in the Home Assistant settings, as password.

**Comment by gnyers** [comment]
Came across the same problem: whatever I type in the login screen is incorrect. 

For new users (like myself) it's not at all clear what URL and password one should enter. If changing the behaviour is too much work for now, fine, but could someone please elaborate how this long-term token can be obtained.

**Comment by Maxr1998** [comment]
Sorry for the late reply. If you open your user profile in your Home Assistant UI, you can generate a long-lived access token at the bottom of that page. Then, you just use that token as your password.

**Comment by maxolasersquad** [comment]
I just tried logging in using the app with putting in a long-lived token and it failed to authenticate. I'm not sure if their login api has recently changed.

**Comment by Maxr1998** [comment]
Hm, that's weird. I don't have my Home Assistant instance available currently, I'll take a look into it soon.

**Comment by SimonMellerin** [comment]
Has someone found a solution on this ?

Can't login with a fresh install of hass with a long term token :/

**Comment by fedaykin** [comment]
Can confirm: long term token is to be treated as Bearer Token. Doesn't work when in password field when targetting HA v100.0+

**Comment by Maxr1998** [comment]
Interesting, I'll look into it once I find time.

**Comment by r-vit** [comment]
Is this app abandoned or changed the license? The latest version in GPlay is 1.2 while here it is 1.0 and looks like there's no commits being done since forever. The login process doesn't work. Any point in keeping this app anymore?

**Comment by Maxr1998** [comment]
The App on Google Play is a completely different one (actually the official Android App from Home Assistant, which is mostly a wrapper of the web app + presence detection/location tracking).
This one (HassDroid) hasn't seen any updates in a while, mostly because I don't have the time, but also because the various changes to the Home Assistant system would make it very hard to stay up to date. Especially since this App was never built with the new Lovelace UI in mind I'm not really sure whether I will continue to maintain this app - I might one day return to it, but no promises right now. I'd suggest you to just switch to the official App.
