### ISSUE TITLE
Android battery tracking

### ISSUE THREAD

**Issue by Maxr1998** [Maxr1998/home-assistant-Android#7]
Send battery level to the Hass server every ~5-10 minutes, using AlarmManager or JobScheduler API.

Update: better do that via Intents.

**Comment by swbradshaw** [comment]
These are two seperate items, and thus should be seperate issues. 

For battery, the app should create a receiver for Intent.ACTION_BATTERY_CHANGED. This is what it is for. Polling every 5-10 min is a bad idea. Further, it probably only makes sense to send battery updates when drops are in larger increments (send every 5% drop vs every 1% drop). This could be a user setting in the app.  Also, we should go ahead and consider battery events (phone plugged in, phone fully charged, etc). These could all be statuses that are sent back and updated in HA.  On that note, when the battery is low, the app needs to be kind, and not drain it more by sending mass updates to HA in the background.

Location Tracking - create another issue and we can discuss in there.

**Comment by Maxr1998** [comment]
Very good ideas, this issue was just a draft anyway. I'll look at your suggestions and will try to implement a first version.
