### ISSUE TITLE
App won't sign in again - User gets white screen

### ISSUE THREAD

**Issue by swbradshaw** [Maxr1998/home-assistant-Android#9]
This bug happened after your changes on March 1.

When I launch app now all I see is a white screen.

Logs say:

```
03-20 21:13:30.407 13793-13811/io.homeassistant.android D/HassService: {"ha_version": "0.40.0", "type": "auth_ok"}
03-20 21:13:30.411 13793-13811/io.homeassistant.android D/HassService: {"success": false, "id": null, "type": "result", "error": {"code": 2, "message": "Message incorrectly formatted: not a valid value for dictionary value @ data['type']. Got 'auth'\nrequired key not provided @ data['id']. Got None"}}
03-20 21:13:30.412 13793-13811/io.homeassistant.android D/HassService: {"success":false,"id":null,"type":"result","error":{"code":2,"message":"Message incorrectly formatted: not a valid value for dictionary value @ data['type']. Got 'auth'\nrequired key not provided @ data['id']. Got None"}}
```

If I wipe data, and run app again, the app prompts for URL / password. I can login and the app works fine.  After killing the activity, it happens again. I have to tap the refresh icon in the header twice, and it will show the URL/IP and Password prompt again.

**Comment by Maxr1998** [comment]
Gonna look at it. Weird that it tries to authenticate another time.

**Comment by swbradshaw** [comment]
I couldn't figure it out. It's almost like the WebSocket code is sending the auth request twice. Regardless, I can no longer use the app. :-(

**Comment by Maxr1998** [comment]
Could you try the latest version and tell me if it works now?

**Comment by swbradshaw** [comment]
Latest version is the same. White screen after sign in. I debugged this locally and couldn't figure it out. It seems like the app is resending the wrong requests. Perhaps it's something with how I'm building it. I'll try an APK when/it's available. Until then, webview is working for me.

**Comment by Maxr1998** [comment]
OK. Could you tell me what device and Android version you use? Additionally, does your Home Assistant config have any specialities?

**Comment by Maxr1998** [comment]
Fixed in current source, according to @swbradshaw
